/*
-- Query: SELECT * FROM test1.CATEGORY
LIMIT 0, 1000

-- Date: 2014-06-12 06:18
*/
INSERT INTO `CATEGORY` (`ID`,`CATEGORY`) VALUES (5151,'Electrical Engineering');
INSERT INTO `CATEGORY` (`ID`,`CATEGORY`) VALUES (5152,'Computer Engineering');
INSERT INTO `CATEGORY` (`ID`,`CATEGORY`) VALUES (5153,'Bio Engineering');
INSERT INTO `CATEGORY` (`ID`,`CATEGORY`) VALUES (5154,'Civil Engineering');
INSERT INTO `CATEGORY` (`ID`,`CATEGORY`) VALUES (5155,'Mechanical Engineering');
