/*
-- Query: SELECT * FROM test1.FILE_TYPE
LIMIT 0, 1000

-- Date: 2014-06-12 06:19
*/
INSERT INTO `FILE_TYPE` (`ID`,`FILETYPE`) VALUES (5172,'text');
INSERT INTO `FILE_TYPE` (`ID`,`FILETYPE`) VALUES (5173,'word doc');
INSERT INTO `FILE_TYPE` (`ID`,`FILETYPE`) VALUES (5174,'photos');
INSERT INTO `FILE_TYPE` (`ID`,`FILETYPE`) VALUES (5175,'code');
INSERT INTO `FILE_TYPE` (`ID`,`FILETYPE`) VALUES (5176,'video');
INSERT INTO `FILE_TYPE` (`ID`,`FILETYPE`) VALUES (5177,'pdf');
INSERT INTO `FILE_TYPE` (`ID`,`FILETYPE`) VALUES (5178,'cad doc');
INSERT INTO `FILE_TYPE` (`ID`,`FILETYPE`) VALUES (5179,'spreadsheet');
INSERT INTO `FILE_TYPE` (`ID`,`FILETYPE`) VALUES (5180,'powerpoint');
