/*
-- Query: SELECT * FROM test1.MEDIA
LIMIT 0, 1000

-- Date: 2014-06-12 06:19
*/
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5182,'pdf','Energy Made In Uganda','/home/fattymcphatfat/projectMaterials/Project 1 - Energy Made in Uganda/Energy Made In Uganda.pdf',5168);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5183,'word doc','IEEE Foundation Grant Application RD','/home/fattymcphatfat/projectMaterials/Project 1 - Energy Made in Uganda/IEEE Foundation Grant Application RD.docx',5168);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5184,'spreadsheet','IEEE Grant Proposal Budget','/home/fattymcphatfat/projectMaterials/Project 1 - Energy Made in Uganda/IEEE Grant Proposal Budget.xls',5168);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5185,'word doc','Micro-Grid Grant Proposal_EGS Edits','/home/fattymcphatfat/projectMaterials/Project 1 - Energy Made in Uganda/Micro-Grid Grant Proposal_EGS Edits.docx',5168);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5186,'word doc','Micro-Grid in Uganda Amendments','/home/fattymcphatfat/projectMaterials/Project 1 - Energy Made in Uganda/Micro-Grid in Uganda Amendments.docx',5168);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5187,'word doc','Project Profile - Input Info - Energy Made','/home/fattymcphatfat/projectMaterials/Project 1 - Energy Made in Uganda/Project Profile - Input Info - Energy Made.docx',5168);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5188,'powerpoint','Senior Design Conference - Final Slides','/home/fattymcphatfat/projectMaterials/Project 1 - Energy Made in Uganda/Senior Design Conference - Final Slides.pptx',5168);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5210,'photos','Electrochemical Detection of Arsenic Using a Paper-Based Microfluidic Device Poster','/home/fattymcphatfat/projectMaterials/Project 2 - Lab in a Chip/Electrochemical Detection of Arsenic Using a Paper-Based Microfluidic Device Poster.jpg',5201);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5211,'pdf','Labonachipposter','/home/fattymcphatfat/projectMaterials/Project 2 - Lab in a Chip/Labonachipposter.pdf',5201);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5212,'pdf','Mobile Field Testing Lab on a Chip Jessica','/home/fattymcphatfat/projectMaterials/Project 2 - Lab in a Chip/Mobile Field Testing Lab on a Chip Jessica.pdf',5201);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5214,'pdf','Rapid, Affordable, and Point-of-Care Water Monitoring via a Microfluidic DNA Sensor and a Mobile Interface for Global Health ','/home/fattymcphatfat/projectMaterials/Project 2 - Lab in a Chip/Rapid, Affordable, and Point-of-Care Water Monitoring via a Microfluidic DNA Sensor and a Mobile Interface for Global Health .pdf',5201);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5215,'word doc','Project Profile - Input Info - Lab in a Chip','/home/fattymcphatfat/projectMaterials/Project 2 - Lab in a Chip/Project Profile - Input Info - Lab in a Chip.docx',5201);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5221,'word doc','Project Profile','/home/fattymcphatfat/projectMaterials/Project 3 - Emergency Power (Turbines)/Project Profile.docx',5216);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5222,'pdf','Emergency Power For Hospitals in Under-Developed Countries (using building-integrated wind turbine systems)','/home/fattymcphatfat/projectMaterials/Project 3 - Emergency Power (Turbines)/Emergency Power For Hospitals in Under-Developed Countries (using building-integrated wind turbine systems).pdf',5216);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5229,'photos','poster','/home/fattymcphatfat/projectMaterials/Project 4 - Dynamic Heat Poverty Map/poster.jpg',5223);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5230,'pdf','PPT - DynamicPovertyHeatMap','/home/fattymcphatfat/projectMaterials/Project 4 - Dynamic Heat Poverty Map/PPT - DynamicPovertyHeatMap.pdf',5223);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5231,'pdf','Project Profile - DPHM','/home/fattymcphatfat/projectMaterials/Project 4 - Dynamic Heat Poverty Map/Project Profile - DPHM.docx',5223);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5237,'word doc','Abstract for NCIIA Grant Proposal','/home/fattymcphatfat/projectMaterials/Project 5 - Cookstove Project/Abstract for NCIIA Grant Proposal.docx',5232);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5238,'word doc','Letter of Support_Final','/home/fattymcphatfat/projectMaterials/Project 5 - Cookstove Project/Letter of Support_Final.docx',5232);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5239,'word doc','Project Profile - Cookstove','/home/fattymcphatfat/projectMaterials/Project 5 - Cookstove Project/Project Profile - Cookstove.docx',5232);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5240,'word doc','Updated NCIIA Grant Draft_Nov5','/home/fattymcphatfat/projectMaterials/Project 5 - Cookstove Project/Updated NCIIA Grant Draft_Nov5.docx',5232);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5241,'spreadsheet','SPO NCIIA Grant Budget','/home/fattymcphatfat/projectMaterials/Project 5 - Cookstove Project/SPO NCIIA Grant Budget.xls',5232);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5244,'powerpoint','Thermoelectric Cookstove PPT presentation','/home/fattymcphatfat/projectMaterials/Project 5 - Cookstove Project/Thermoelectric Cookstove PPT presentation.ppt',5232);
INSERT INTO `MEDIA` (`ID`,`FILETYPE`,`FILENAME`,`FILELOCATION`,`PID`) VALUES (5245,'pdf','Theremoelectric Cookstove poster 2013 ','/home/fattymcphatfat/projectMaterials/Project 5 - Cookstove Project/Theremoelectric Cookstove poster 2013 .pdf',5232);
