/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package frugalLab;

/**
 *
 * @author Hinsen Chan
 */
public class ManagePanel extends javax.swing.JPanel {
    FrugalController frugalController;

    /**
     * Creates new form ManagePanel2
     */
    public ManagePanel(FrugalController frugalController) {
        initComponents();
        this.frugalController = frugalController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        userManagerButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        projectManagerButton = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        logoutButton = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(143, 19, 21));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        topPanel.setBackground(new java.awt.Color(143, 19, 21));
        topPanel.setPreferredSize(new java.awt.Dimension(1024, 256));

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        add(topPanel);

        buttonPanel.setBackground(new java.awt.Color(143, 19, 21));
        buttonPanel.setPreferredSize(new java.awt.Dimension(1024, 256));
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.PAGE_AXIS));

        userManagerButton.setText("User Management");
        userManagerButton.setAlignmentX(0.5F);
        userManagerButton.setMaximumSize(new java.awt.Dimension(200, 50));
        userManagerButton.setPreferredSize(new java.awt.Dimension(200, 50));
        userManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManagerButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(userManagerButton);
        buttonPanel.add(filler1);

        projectManagerButton.setText("Project Management");
        projectManagerButton.setAlignmentX(0.5F);
        projectManagerButton.setMaximumSize(new java.awt.Dimension(200, 50));
        projectManagerButton.setPreferredSize(new java.awt.Dimension(200, 50));
        projectManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectManagerButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(projectManagerButton);
        buttonPanel.add(filler2);

        logoutButton.setText("Logout");
        logoutButton.setAlignmentX(0.5F);
        logoutButton.setMaximumSize(new java.awt.Dimension(200, 50));
        logoutButton.setPreferredSize(new java.awt.Dimension(200, 50));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(logoutButton);

        add(buttonPanel);

        bottomPanel.setBackground(new java.awt.Color(143, 19, 21));
        bottomPanel.setPreferredSize(new java.awt.Dimension(1024, 256));

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        add(bottomPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void userManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagerButtonActionPerformed
        frugalController.launchUserManagerPanel();
    }//GEN-LAST:event_userManagerButtonActionPerformed

    private void projectManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectManagerButtonActionPerformed
        frugalController.launchProjectPanel();
    }//GEN-LAST:event_projectManagerButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        frugalController.launchLoginPanel();
    }//GEN-LAST:event_logoutButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton projectManagerButton;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton userManagerButton;
    // End of variables declaration//GEN-END:variables
}
