/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package frugalLab;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Administrator
 */
public class ResultPanel extends javax.swing.JPanel {
    private FrugalController frugalController;

    /**
     * Creates new form ResultPanel
     */
    public ResultPanel(FrugalController frugalController) {
        initComponents();
        this.frugalController = frugalController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        resultPanel = new javax.swing.JPanel();
        statPanel = new javax.swing.JPanel();

        tabbedPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Results", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        resultPanel.setLayout(new java.awt.CardLayout());
        tabbedPane.addTab("Search Results", resultPanel);

        statPanel.setLayout(new java.awt.CardLayout());
        tabbedPane.addTab("Search Stats", statPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel resultPanel;
    private javax.swing.JPanel statPanel;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the resultPanel
     */
    public javax.swing.JPanel getResultPanel() {
        return resultPanel;
    }

    /**
     * @param resultPanel the resultPanel to set
     */
    public void setResultPanel(javax.swing.JPanel resultPanel) {
        this.resultPanel = resultPanel;
    }

    /**
     * @return the statPanel
     */
    public javax.swing.JPanel getStatPanel() {
        return statPanel;
    }

    /**
     * @param statPanel the statPanel to set
     */
    public void setStatPanel(javax.swing.JPanel statPanel) {
        this.statPanel = statPanel;
    }
}
