/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package frugalLab;

/**
 *
 * @author fattymcphatfat
 */
public class StatPanel extends javax.swing.JPanel {
    private FrugalController frugalController;

    /**
     * Creates new form StatPanel
     */
    public StatPanel(FrugalController frugalController) {
        initComponents();
        this.frugalController = frugalController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        leftLabelPanel = new javax.swing.JPanel();
        startDateLabel = new javax.swing.JLabel();
        projectCountLabel = new javax.swing.JLabel();
        categoryCountLabel = new javax.swing.JLabel();
        tagCountLabel = new javax.swing.JLabel();
        projectCountLabel1 = new javax.swing.JLabel();
        leftFieldPanel = new javax.swing.JPanel();
        startDateTextField = new javax.swing.JTextField();
        projectCountTextField = new javax.swing.JTextField();
        categoryCountScrollPane = new javax.swing.JScrollPane();
        categoryCountTextArea = new javax.swing.JTextArea();
        tagCountScrollPane = new javax.swing.JScrollPane();
        tagCountTextArea = new javax.swing.JTextArea();
        categoryCountScrollPane1 = new javax.swing.JScrollPane();
        categoryCountTextArea1 = new javax.swing.JTextArea();
        rightPanel = new javax.swing.JPanel();
        rightLabelPanel = new javax.swing.JPanel();
        endDateLabel = new javax.swing.JLabel();
        studentsCountLabel = new javax.swing.JLabel();
        partnersCountLabel = new javax.swing.JLabel();
        advisorsCountLabel = new javax.swing.JLabel();
        rightFieldPanel = new javax.swing.JPanel();
        endDateTextField = new javax.swing.JTextField();
        partnersCountScrollPane = new javax.swing.JScrollPane();
        partnersCountTextArea = new javax.swing.JTextArea();
        advisorsCountScrollPane = new javax.swing.JScrollPane();
        advisorsCountTextArea = new javax.swing.JTextArea();
        studentsCountScrollPane = new javax.swing.JScrollPane();
        studentsCountTextArea = new javax.swing.JTextArea();
        separatorPanel = new javax.swing.JPanel();
        separator = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(143, 19, 21));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        leftPanel.setBackground(new java.awt.Color(143, 19, 21));
        leftPanel.setPreferredSize(new java.awt.Dimension(479, 744));

        leftLabelPanel.setBackground(new java.awt.Color(143, 19, 21));

        startDateLabel.setBackground(new java.awt.Color(143, 19, 21));
        startDateLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        startDateLabel.setForeground(java.awt.Color.white);
        startDateLabel.setText("Start Date:");
        startDateLabel.setOpaque(true);

        projectCountLabel.setBackground(new java.awt.Color(143, 19, 21));
        projectCountLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        projectCountLabel.setForeground(java.awt.Color.white);
        projectCountLabel.setText("Project Count:");
        projectCountLabel.setOpaque(true);

        categoryCountLabel.setBackground(new java.awt.Color(143, 19, 21));
        categoryCountLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        categoryCountLabel.setForeground(java.awt.Color.white);
        categoryCountLabel.setText("Category Count:");
        categoryCountLabel.setOpaque(true);

        tagCountLabel.setBackground(new java.awt.Color(143, 19, 21));
        tagCountLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        tagCountLabel.setForeground(java.awt.Color.white);
        tagCountLabel.setText("Tag Count:");
        tagCountLabel.setOpaque(true);

        projectCountLabel1.setBackground(new java.awt.Color(143, 19, 21));
        projectCountLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        projectCountLabel1.setForeground(java.awt.Color.white);
        projectCountLabel1.setText("Status Count:");
        projectCountLabel1.setOpaque(true);

        javax.swing.GroupLayout leftLabelPanelLayout = new javax.swing.GroupLayout(leftLabelPanel);
        leftLabelPanel.setLayout(leftLabelPanelLayout);
        leftLabelPanelLayout.setHorizontalGroup(
            leftLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLabelPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(leftLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startDateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(projectCountLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(projectCountLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(categoryCountLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tagCountLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftLabelPanelLayout.setVerticalGroup(
            leftLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLabelPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(startDateLabel)
                .addGap(45, 45, 45)
                .addComponent(projectCountLabel)
                .addGap(43, 43, 43)
                .addComponent(projectCountLabel1)
                .addGap(175, 175, 175)
                .addComponent(categoryCountLabel)
                .addGap(174, 174, 174)
                .addComponent(tagCountLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        leftFieldPanel.setBackground(new java.awt.Color(143, 19, 21));
        leftFieldPanel.setPreferredSize(new java.awt.Dimension(221, 253));

        startDateTextField.setMinimumSize(new java.awt.Dimension(86, 27));

        categoryCountTextArea.setColumns(20);
        categoryCountTextArea.setRows(5);
        categoryCountScrollPane.setViewportView(categoryCountTextArea);

        tagCountTextArea.setColumns(20);
        tagCountTextArea.setRows(5);
        tagCountScrollPane.setViewportView(tagCountTextArea);

        categoryCountTextArea1.setColumns(20);
        categoryCountTextArea1.setRows(5);
        categoryCountScrollPane1.setViewportView(categoryCountTextArea1);

        javax.swing.GroupLayout leftFieldPanelLayout = new javax.swing.GroupLayout(leftFieldPanel);
        leftFieldPanel.setLayout(leftFieldPanelLayout);
        leftFieldPanelLayout.setHorizontalGroup(
            leftFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftFieldPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(leftFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tagCountScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(categoryCountScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(categoryCountScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(projectCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        leftFieldPanelLayout.setVerticalGroup(
            leftFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftFieldPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(projectCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(categoryCountScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(categoryCountScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(tagCountScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftLabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leftFieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftLabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftFieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
                .addContainerGap())
        );

        rightPanel.setBackground(new java.awt.Color(143, 19, 21));

        rightLabelPanel.setBackground(new java.awt.Color(143, 19, 21));

        endDateLabel.setBackground(new java.awt.Color(143, 19, 21));
        endDateLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        endDateLabel.setForeground(java.awt.Color.white);
        endDateLabel.setText("End Date:");
        endDateLabel.setOpaque(true);

        studentsCountLabel.setBackground(new java.awt.Color(143, 19, 21));
        studentsCountLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        studentsCountLabel.setForeground(java.awt.Color.white);
        studentsCountLabel.setText("Students Count:");
        studentsCountLabel.setOpaque(true);

        partnersCountLabel.setBackground(new java.awt.Color(143, 19, 21));
        partnersCountLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        partnersCountLabel.setForeground(java.awt.Color.white);
        partnersCountLabel.setText("Partners Count:");
        partnersCountLabel.setOpaque(true);

        advisorsCountLabel.setBackground(new java.awt.Color(143, 19, 21));
        advisorsCountLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        advisorsCountLabel.setForeground(java.awt.Color.white);
        advisorsCountLabel.setText("Advisors Count:");
        advisorsCountLabel.setOpaque(true);

        javax.swing.GroupLayout rightLabelPanelLayout = new javax.swing.GroupLayout(rightLabelPanel);
        rightLabelPanel.setLayout(rightLabelPanelLayout);
        rightLabelPanelLayout.setHorizontalGroup(
            rightLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLabelPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rightLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endDateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(studentsCountLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(advisorsCountLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(partnersCountLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rightLabelPanelLayout.setVerticalGroup(
            rightLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLabelPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(endDateLabel)
                .addGap(53, 53, 53)
                .addComponent(studentsCountLabel)
                .addGap(180, 180, 180)
                .addComponent(partnersCountLabel)
                .addGap(180, 180, 180)
                .addComponent(advisorsCountLabel)
                .addGap(175, 175, 175))
        );

        rightFieldPanel.setBackground(new java.awt.Color(143, 19, 21));
        rightFieldPanel.setPreferredSize(new java.awt.Dimension(221, 253));

        endDateTextField.setMinimumSize(new java.awt.Dimension(86, 27));

        partnersCountTextArea.setColumns(20);
        partnersCountTextArea.setRows(5);
        partnersCountScrollPane.setViewportView(partnersCountTextArea);

        advisorsCountTextArea.setColumns(20);
        advisorsCountTextArea.setRows(5);
        advisorsCountScrollPane.setViewportView(advisorsCountTextArea);

        studentsCountTextArea.setColumns(20);
        studentsCountTextArea.setRows(5);
        studentsCountScrollPane.setViewportView(studentsCountTextArea);

        javax.swing.GroupLayout rightFieldPanelLayout = new javax.swing.GroupLayout(rightFieldPanel);
        rightFieldPanel.setLayout(rightFieldPanelLayout);
        rightFieldPanelLayout.setHorizontalGroup(
            rightFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightFieldPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rightFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(studentsCountScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(partnersCountScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rightFieldPanelLayout.createSequentialGroup()
                        .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(advisorsCountScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        rightFieldPanelLayout.setVerticalGroup(
            rightFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightFieldPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(studentsCountScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(partnersCountScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(advisorsCountScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rightLabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightFieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightLabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rightFieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
                .addContainerGap())
        );

        separatorPanel.setBackground(new java.awt.Color(143, 19, 21));

        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout separatorPanelLayout = new javax.swing.GroupLayout(separatorPanel);
        separatorPanel.setLayout(separatorPanelLayout);
        separatorPanelLayout.setHorizontalGroup(
            separatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(separatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(separatorPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        separatorPanelLayout.setVerticalGroup(
            separatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(separatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(separatorPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(separator, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(separatorPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advisorsCountLabel;
    private javax.swing.JScrollPane advisorsCountScrollPane;
    private javax.swing.JTextArea advisorsCountTextArea;
    private javax.swing.JLabel categoryCountLabel;
    private javax.swing.JScrollPane categoryCountScrollPane;
    private javax.swing.JScrollPane categoryCountScrollPane1;
    private javax.swing.JTextArea categoryCountTextArea;
    private javax.swing.JTextArea categoryCountTextArea1;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JTextField endDateTextField;
    private javax.swing.JPanel leftFieldPanel;
    private javax.swing.JPanel leftLabelPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel partnersCountLabel;
    private javax.swing.JScrollPane partnersCountScrollPane;
    private javax.swing.JTextArea partnersCountTextArea;
    private javax.swing.JLabel projectCountLabel;
    private javax.swing.JLabel projectCountLabel1;
    private javax.swing.JTextField projectCountTextField;
    private javax.swing.JPanel rightFieldPanel;
    private javax.swing.JPanel rightLabelPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JSeparator separator;
    private javax.swing.JPanel separatorPanel;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JTextField startDateTextField;
    private javax.swing.JLabel studentsCountLabel;
    private javax.swing.JScrollPane studentsCountScrollPane;
    private javax.swing.JTextArea studentsCountTextArea;
    private javax.swing.JLabel tagCountLabel;
    private javax.swing.JScrollPane tagCountScrollPane;
    private javax.swing.JTextArea tagCountTextArea;
    // End of variables declaration//GEN-END:variables
}
